"use client";

import { OrbitControls, useGLTF } from "@react-three/drei";

import { Canvas } from "@react-three/fiber";

export const Tshirt = () => {
  const { nodes, materials } = useGLTF("t-shirt.glb");

  return (
    <Canvas>
      <group>
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Body_Back_2_Node.geometry}
          material={nodes.Body_Back_2_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Body_Back_Node001.geometry}
          material={nodes.Body_Back_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Body_Front_1_Node001.geometry}
          material={nodes.Body_Front_1_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Body_Front_4_Node.geometry}
          material={nodes.Body_Front_4_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Pattern_190323_Node001.geometry}
          material={nodes.Pattern_190323_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Pattern_233998_Node001.geometry}
          material={nodes.Pattern_233998_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Sleeves_2_Node001.geometry}
          material={nodes.Sleeves_2_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Sleeves_3_Node001.geometry}
          material={nodes.Sleeves_3_Node001.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1132971_Node.geometry}
          material={nodes.StitchMatShape_1132971_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133112_Node.geometry}
          material={nodes.StitchMatShape_1133112_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133222_Node.geometry}
          material={nodes.StitchMatShape_1133222_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133332_Node.geometry}
          material={nodes.StitchMatShape_1133332_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133475_Node.geometry}
          material={nodes.StitchMatShape_1133475_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133618_Node.geometry}
          material={nodes.StitchMatShape_1133618_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133679_Node.geometry}
          material={nodes.StitchMatShape_1133679_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133740_Node.geometry}
          material={nodes.StitchMatShape_1133740_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1133886_Node.geometry}
          material={nodes.StitchMatShape_1133886_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134029_Node.geometry}
          material={nodes.StitchMatShape_1134029_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134076_Node.geometry}
          material={nodes.StitchMatShape_1134076_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134123_Node.geometry}
          material={nodes.StitchMatShape_1134123_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134170_Node.geometry}
          material={nodes.StitchMatShape_1134170_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134217_Node.geometry}
          material={nodes.StitchMatShape_1134217_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134308_Node.geometry}
          material={nodes.StitchMatShape_1134308_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134390_Node.geometry}
          material={nodes.StitchMatShape_1134390_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134472_Node.geometry}
          material={nodes.StitchMatShape_1134472_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134554_Node.geometry}
          material={nodes.StitchMatShape_1134554_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134765_Node.geometry}
          material={nodes.StitchMatShape_1134765_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134856_Node.geometry}
          material={nodes.StitchMatShape_1134856_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1134938_Node.geometry}
          material={nodes.StitchMatShape_1134938_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135020_Node.geometry}
          material={nodes.StitchMatShape_1135020_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135102_Node.geometry}
          material={nodes.StitchMatShape_1135102_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135313_Node.geometry}
          material={nodes.StitchMatShape_1135313_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135573_Node.geometry}
          material={nodes.StitchMatShape_1135573_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135599_Node.geometry}
          material={nodes.StitchMatShape_1135599_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135622_Node.geometry}
          material={nodes.StitchMatShape_1135622_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135641_Node.geometry}
          material={nodes.StitchMatShape_1135641_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135660_Node.geometry}
          material={nodes.StitchMatShape_1135660_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135679_Node.geometry}
          material={nodes.StitchMatShape_1135679_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135695_Node.geometry}
          material={nodes.StitchMatShape_1135695_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135838_Node.geometry}
          material={nodes.StitchMatShape_1135838_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1135981_Node.geometry}
          material={nodes.StitchMatShape_1135981_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1136127_Node.geometry}
          material={nodes.StitchMatShape_1136127_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.StitchMatShape_1136270_Node.geometry}
          material={nodes.StitchMatShape_1136270_Node.material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.base_footb_Scene_Node.geometry}
          material={nodes.base_footb_Scene_Node.material}
        />
      </group>
      <OrbitControls
        minPolarAngle={Math.PI / 2}
        maxPolarAngle={Math.PI / 2}
        enableZoom={false}
        enablePan={false}
      />
    </Canvas>
  );
};
